"""Render fragility-radar reports for email (full) and Telegram (digest).

Numbers are pre-computed; this module only formats them. The optional LLM
narrative is appended verbatim when present.
"""
from __future__ import annotations

from datetime import date

from ..options.types import Event
from . import actions
from .types import BAND_LABELS_CN, BAND_ORDER, FragilityScore, SystemicGate

_BAND_EMOJI = {"Normal": "🟢", "Watch": "🟡", "Alert": "🟠", "Critical": "🔴"}


def _worst_band(scores: list[FragilityScore]) -> str:
    if not scores:
        return "Normal"
    return max(scores, key=lambda s: BAND_ORDER[s.band]).band


def _f(v: float | None, dp: int = 2) -> str:
    return "n/a" if v is None else f"{v:.{dp}f}"


def _delta(v: float | None) -> str:
    return "" if v is None else f"{v:+.0f}"


def render_telegram(
    scores: list[FragilityScore],
    *,
    today: date,
    narrative: str | None = None,
    top_n: int = 6,
) -> str:
    """Compact daily digest for Telegram."""
    if not scores:
        return f"*[Fragility Radar]* {today}\nNo instruments scored (check data sources)."

    worst = _worst_band(scores)
    ordered = sorted(scores, key=lambda s: s.score, reverse=True)
    lines = [f"{_BAND_EMOJI[worst]} *[Fragility Radar: {worst}]* {today}"]
    for s in ordered[:top_n]:
        d = _delta(s.delta_3d)
        d = f" ({d}/3d)" if d else ""
        lines.append(f"{_BAND_EMOJI[s.band]} {s.symbol} {s.score}{d} — {s.band}")

    flagged = [s for s in ordered if BAND_ORDER[s.band] >= BAND_ORDER["Alert"]]
    if flagged:
        lines.append("")
        for s in flagged[:3]:
            lines.append(f"*{s.symbol}*: {actions.POSTURE[s.band]}")
    if narrative:
        lines.append("")
        lines.append(narrative[:600])
    return "\n".join(lines)


def render_email(
    scores: list[FragilityScore],
    gate: SystemicGate,
    events: list[Event],
    *,
    today: date,
    narrative: str | None = None,
    ledger_stats: dict | None = None,
) -> tuple[str, str]:
    """Return (subject, markdown body) for the full report."""
    worst = _worst_band(scores)
    ordered = sorted(scores, key=lambda s: s.score, reverse=True)
    flagged = [s for s in ordered if BAND_ORDER[s.band] >= BAND_ORDER["Alert"]]

    top = ordered[0] if ordered else None
    subject = (
        f"[Fragility Radar: {worst}] "
        + (f"{top.symbol} {top.score}" if top else "no data")
        + f" — {today}"
    )

    lines: list[str] = [
        f"# Trend Flash-Crash Radar — {today}",
        "",
        f"## Market regime: systemic multiplier {gate.multiplier:.2f}",
        "",
    ]
    if gate.reasons:
        lines += [f"- {r}" for r in gate.reasons] + [""]

    # Scoreboard
    lines += ["## Fragility scoreboard", ""]
    lines.append("| # | Symbol | Cluster | Score | Band | A | B | C | Δ3d | Conf |")
    lines.append("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    for s in ordered:
        lines.append(
            f"| {s.rank or ''} | {s.symbol} | {s.cluster or ''} | **{s.score}** "
            f"| {s.band} {BAND_LABELS_CN[s.band]} | {_f(s.pillar_a)} | {_f(s.pillar_b)} "
            f"| {_f(s.pillar_c)} | {_delta(s.delta_3d)} | {s.confidence:.0%} |"
        )
    lines.append("")

    # Flagged-name detail
    if flagged:
        lines += ["## Flagged names — posture & falsification", ""]
        for s in flagged:
            rec = actions.recommendation(s, ledger_stats)
            lines += [
                f"### {_BAND_EMOJI[s.band]} {s.symbol} — {s.score}/100 ({s.band})",
                "",
                f"**Action:** {rec['posture']}",
                "",
                f"_{rec['falsification']}_",
                "",
                f"_{rec['base_rate']}_",
                "",
            ]
            if s.reasons:
                lines += ["Triggered signals:"] + [f"- {r}" for r in s.reasons] + [""]

    # Catalysts
    lines += ["## Upcoming catalysts", ""]
    if events:
        lines.append("| Date | Event | Importance |")
        lines.append("| --- | --- | --- |")
        for e in events:
            lines.append(f"| {e.date} | {e.label} | {e.importance} |")
    else:
        lines.append("No major scheduled catalysts this week.")
    lines.append("")

    # LLM narrative
    if narrative:
        lines += ["## Red-team briefing", "", narrative, ""]

    lines += [
        "---",
        "*Generated by HongQuant Trend Flash-Crash Radar. Conditional fragility, "
        "not a timing signal — sizes positions and hedges, never entries/exits.*",
    ]
    return subject, "\n".join(lines)
